services:
  mcp-gateway-github:
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --verbose
      - --transport=streaming
      - --servers=github
      - --port=8080
    ports:
      - '8080:8080'
  app:
    build: .
    command: python app.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mcp-gateway-github
