name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/ai-agent-app
  DOCKER_HUB_IMAGE: ${{ github.repository_owner }}/ai-agent-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: docker login ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build images
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker build -t $DOCKER_HUB_IMAGE:${{ github.sha }} .
          docker compose build
      - name: push images
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:${{ github.sha }} $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest
          docker tag $DOCKER_HUB_IMAGE:${{ github.sha }} $DOCKER_HUB_IMAGE:latest
          docker push $DOCKER_HUB_IMAGE:${{ github.sha }}
          docker push $DOCKER_HUB_IMAGE:latest
      - name: docker compose up
        run: docker compose up -d
      - name: health check
        run: docker ps -a
      - name: stop
        if: always()
        run: docker compose down -v
