name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/ai-agent-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: docker login
        run: echo $PERSONAL_TOKEN | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: build images
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker compose build
      - name: push images
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:${{ github.sha }} $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest
      - name: docker compose up
        run: docker compose up -d
      - name: health check
        run: docker ps -a
      - name: stop
        if: always()
        run: docker compose down -v
